export default [
  {section: "Especiais", name: "Panini Knight Logo"},
  {section: "Especiais", name: "Logo"},
  {section: "Especiais", name: "World Cup Trophy"},
  {section: "Especiais", name: "’18 World Cup Graphic Top"},
  {section: "Especiais", name: "’18 World Cup Graphic Bottom"},
  {section: "Especiais", name: "’18 World Cup Logo Top"},
  {section: "Especiais", name: "’18 World Cup Logo Bottom"},
  {section: "Especiais", name: "adidas Official Ball"},
  {section: "Estádios", name: "Ekaterinburg Arena"},
  {section: "Estádios", name: "Kaliningrad Stadium"},
  {section: "Estádios", name: "Kazan Arena"},
  {section: "Estádios", name: "Spartak Stadium"},
  {section: "Estádios", name: "Nizhny Novgorod Stadium"},
  {section: "Estádios", name: "Luzhniki Stadium"},
  {section: "Estádios", name: "Rostov Arena"},
  {section: "Estádios", name: "Saint Petersburg Stadium"},
  {section: "Estádios", name: "Samara Arena"},
  {section: "Estádios", name: "Mordovia Arena"},
  {section: "Estádios", name: "Fisht Stadium"},
  {section: "Estádios", name: "Volgograd Arena"},
  {section: "Cidades", name: "Moscow Host City Poster part 1"},
  {section: "Cidades", name: "Moscow Host City Poster part 2"},
  {section: "Cidades", name: "Kaliningrad Host City Poster"},
  {section: "Cidades", name: "Saint Petersburg Host City Poster"},
  {section: "Cidades", name: "Sochi Host City Poster"},
  {section: "Cidades", name: "Rostov-On-Don Host City Poster"},
  {section: "Cidades", name: "Volgograd Host City Poster"},
  {section: "Cidades", name: "Kazan Host City Poster"},
  {section: "Cidades", name: "Nizhny Novgorod Host City Poster"},
  {section: "Cidades", name: "Samara Host City Poster"},
  {section: "Cidades", name: "Ekaterinburg Host City Poster"},
  {section: "Cidades", name: "Saransk Host City Poster"},
  {section: "Rússia", name: "Russia Team Logo"},
  {section: "Rússia", name: "Russia Team Photo"},
  {section: "Rússia", name: "Igor Akinfeev"},
  {section: "Rússia", name: "Igor Smolnikov"},
  {section: "Rússia", name: "Viktor Vasin"},
  {section: "Rússia", name: "Mario Fernandes"},
  {section: "Rússia", name: "Fedor Kudryashov"},
  {section: "Rússia", name: "Ilya Kutepov"},
  {section: "Rússia", name: "Dmitri Kombarov"},
  {section: "Rússia", name: "Aleksei Miranchuk"},
  {section: "Rússia", name: "Denis Glushakov"},
  {section: "Rússia", name: "Aleksandr Golovin"},
  {section: "Rússia", name: "Yuri Zhirkov"},
  {section: "Rússia", name: "Aleksandr Samedov"},
  {section: "Rússia", name: "Aleksandr Erokhin"},
  {section: "Rússia", name: "Alan Dzagoev"},
  {section: "Rússia", name: "Daler Kuzyayev"},
  {section: "Rússia", name: "Dmitry Poloz"},
  {section: "Rússia", name: "Fedor Smolov"},
  {section: "Rússia", name: "Aleksandr Kokorin"},
  {section: "Arábia Saudita", name: "Saudi Arabia Team Logo"},
  {section: "Arábia Saudita", name: "Saudi Arabia Team Photo"},
  {section: "Arábia Saudita", name: "Abdullah Al-Mayouf"},
  {section: "Arábia Saudita", name: "Osama Hawsawi"},
  {section: "Arábia Saudita", name: "Abdullah Al-Zori"},
  {section: "Arábia Saudita", name: "Mansour Al-Harbi"},
  {section: "Arábia Saudita", name: "Omar Hawsawi"},
  {section: "Arábia Saudita", name: "Yasser Al-Shahrani"},
  {section: "Arábia Saudita", name: "Motaz Hawsawi"},
  {section: "Arábia Saudita", name: "Mohammed Al-Beraik"},
  {section: "Arábia Saudita", name: "Taisir Al-Jassim"},
  {section: "Arábia Saudita", name: "Salman Al-Faraj"},
  {section: "Arábia Saudita", name: "Abdulmalek Al-Khaibri"},
  {section: "Arábia Saudita", name: "Salman Al-Moasher"},
  {section: "Arábia Saudita", name: "Yahya Al-Shehri"},
  {section: "Arábia Saudita", name: "Salem Al-Dosari"},
  {section: "Arábia Saudita", name: "Nawaf Al-Abed"},
  {section: "Arábia Saudita", name: "Mohammad Al-Sahlawi"},
  {section: "Arábia Saudita", name: "Nasser Al-Shamrani"},
  {section: "Arábia Saudita", name: "Fahad Al-Muwallad"},
  {section: "Egito", name: "Egypt Team Logo"},
  {section: "Egito", name: "Egypt Team Photo"},
  {section: "Egito", name: "Essam El Hadary"},
  {section: "Egito", name: "Ali Gabr"},
  {section: "Egito", name: "Ahmed Elmohamady"},
  {section: "Egito", name: "Omar Gaber"},
  {section: "Egito", name: "Ramy Rabia"},
  {section: "Egito", name: "Ahmed Hegazi"},
  {section: "Egito", name: "Ahmed Abdelmonem Fathy"},
  {section: "Egito", name: "Mohamed Abdel Shafy"},
  {section: "Egito", name: "Saad El-Din Samir"},
  {section: "Egito", name: "Tarek Hamed"},
  {section: "Egito", name: "Mahmoud Kahraba"},
  {section: "Egito", name: "Mohamed Elneny"},
  {section: "Egito", name: "Trezeguet"},
  {section: "Egito", name: "Abdallah El Said"},
  {section: "Egito", name: "Ramadan Sobhi"},
  {section: "Egito", name: "Ahmed Hassan"},
  {section: "Egito", name: "Mohamed Salah"},
  {section: "Egito", name: "Amr Gamal"},
  {section: "Uruguai", name: "Uruguay Team Logo"},
  {section: "Uruguai", name: "Uruguay Team Photo"},
  {section: "Uruguai", name: "Fernando Muslera"},
  {section: "Uruguai", name: "Maxi Pereira"},
  {section: "Uruguai", name: "Diego Godin"},
  {section: "Uruguai", name: "Martin Caceres"},
  {section: "Uruguai", name: "Jose Gimenez"},
  {section: "Uruguai", name: "Sebastian Coates"},
  {section: "Uruguai", name: "Gaston Silva"},
  {section: "Uruguai", name: "Mathias Corujo"},
  {section: "Uruguai", name: "Egidio Arevalo Rios"},
  {section: "Uruguai", name: "Alvaro Gonzalez"},
  {section: "Uruguai", name: "Nicolas Lodeiro"},
  {section: "Uruguai", name: "Carlos Sanchez"},
  {section: "Uruguai", name: "Cristian Rodriguez"},
  {section: "Uruguai", name: "Matias Vecino"},
  {section: "Uruguai", name: "Edinson Cavani"},
  {section: "Uruguai", name: "Luis Suarez"},
  {section: "Uruguai", name: "Cristhian Stuani"},
  {section: "Uruguai", name: "Diego Rolan"},
  {section: "Portugal", name: "Portugal Team Logo"},
  {section: "Portugal", name: "Portugal Team Photo"},
  {section: "Portugal", name: "Rui Patricio"},
  {section: "Portugal", name: "Bruno Alves"},
  {section: "Portugal", name: "Pepe"},
  {section: "Portugal", name: "Jose Fonte"},
  {section: "Portugal", name: "Eliseu"},
  {section: "Portugal", name: "Cedric"},
  {section: "Portugal", name: "Raphael Guerreiro"},
  {section: "Portugal", name: "Joao Moutinho"},
  {section: "Portugal", name: "Joao Mario"},
  {section: "Portugal", name: "Danilo Pereira"},
  {section: "Portugal", name: "William Carvalho"},
  {section: "Portugal", name: "Andre Gomes"},
  {section: "Portugal", name: "Ricardo Quaresma"},
  {section: "Portugal", name: "Bernardo Silva"},
  {section: "Portugal", name: "Andre Silva"},
  {section: "Portugal", name: "Gelson Martins"},
  {section: "Portugal", name: "Cristiano Ronaldo"},
  {section: "Portugal", name: "Nani"},
  {section: "Espanha", name: "Spain Team Logo"},
  {section: "Espanha", name: "Spain Team Photo"},
  {section: "Espanha", name: "David de Gea"},
  {section: "Espanha", name: "Jordi Alba"},
  {section: "Espanha", name: "Nacho"},
  {section: "Espanha", name: "Nacho Monreal"},
  {section: "Espanha", name: "Gerard Pique"},
  {section: "Espanha", name: "Sergio Ramos"},
  {section: "Espanha", name: "Daniel Carvajal"},
  {section: "Espanha", name: "Sergio Busquets"},
  {section: "Espanha", name: "Thiago"},
  {section: "Espanha", name: "Isco"},
  {section: "Espanha", name: "Koke"},
  {section: "Espanha", name: "Marco Asensio"},
  {section: "Espanha", name: "Andres Iniesta"},
  {section: "Espanha", name: "David Silva"},
  {section: "Espanha", name: "Saul Niguez"},
  {section: "Espanha", name: "Alvaro Morata"},
  {section: "Espanha", name: "Vitolo"},
  {section: "Espanha", name: "Diego Costa"},
  {section: "Marrocos", name: "Morocco Team Logo"},
  {section: "Marrocos", name: "Morocco Team Photo"},
  {section: "Marrocos", name: "Munir Mohamedi"},
  {section: "Marrocos", name: "Medhi Benatia"},
  {section: "Marrocos", name: "Nabil Dirar"},
  {section: "Marrocos", name: "Romain Saiss"},
  {section: "Marrocos", name: "Fouad Chafik"},
  {section: "Marrocos", name: "Hamza Mendyl"},
  {section: "Marrocos", name: "Achraf Hakimi"},
  {section: "Marrocos", name: "Mbark Boussoufa"},
  {section: "Marrocos", name: "Karim El Ahmadi"},
  {section: "Marrocos", name: "Younes Belhanda"},
  {section: "Marrocos", name: "Nordin Amrabat"},
  {section: "Marrocos", name: "Faycal Fajr"},
  {section: "Marrocos", name: "Hakim Ziyech"},
  {section: "Marrocos", name: "Youssef Ait Bennasser"},
  {section: "Marrocos", name: "Khalid Boutaib"},
  {section: "Marrocos", name: "Rachid Alioui"},
  {section: "Marrocos", name: "Aziz Bouhaddouz"},
  {section: "Marrocos", name: "Youssef En-Nesyri"},
  {section: "Irã", name: "Iran Team Logo"},
  {section: "Irã", name: "Iran Team Photo"},
  {section: "Irã", name: "Alireza Beiranvand"},
  {section: "Irã", name: "Pejman Montazeri"},
  {section: "Irã", name: "Vouria Ghafouri"},
  {section: "Irã", name: "Jalal Hosseini"},
  {section: "Irã", name: "Milad Mohammadi"},
  {section: "Irã", name: "Morteza Pouraliganji"},
  {section: "Irã", name: "Ramin Rezaeian"},
  {section: "Irã", name: "Ehsan Hajsafi"},
  {section: "Irã", name: "Omid Ebrahimi"},
  {section: "Irã", name: "Saeid Ezatolahi"},
  {section: "Irã", name: "Vahid Amiri"},
  {section: "Irã", name: "Alireza Jahanbakhsh"},
  {section: "Irã", name: "Ashkan Dejagah"},
  {section: "Irã", name: "Saman Ghoddos"},
  {section: "Irã", name: "Mehdi Taremi"},
  {section: "Irã", name: "Karim Ansarifard"},
  {section: "Irã", name: "Reza Ghoochannejhad"},
  {section: "Irã", name: "Sardar Azmoun"},
  {section: "França", name: "France Team Logo"},
  {section: "França", name: "France Team Photo"},
  {section: "França", name: "Hugo Lloris"},
  {section: "França", name: "Raphael Varane"},
  {section: "França", name: "Lucas Digne"},
  {section: "França", name: "Djibril Sidibe"},
  {section: "França", name: "Samuel Umtiti"},
  {section: "França", name: "Layvin Kurzawa"},
  {section: "França", name: "Laurent Koscielny"},
  {section: "França", name: "Blaise Matuidi"},
  {section: "França", name: "N’Golo Kante"},
  {section: "França", name: "Thomas Lemar"},
  {section: "França", name: "Adrien Rabiot"},
  {section: "França", name: "Paul Pogba"},
  {section: "França", name: "Olivier Giroud"},
  {section: "França", name: "Antoine Griezmann"},
  {section: "França", name: "Alexandre Lacazette"},
  {section: "França", name: "Kylian Mbappe"},
  {section: "França", name: "Ousmane Dembele"},
  {section: "França", name: "Anthony Martial"},
  {section: "Austrália", name: "Australia Team Logo"},
  {section: "Austrália", name: "Australia Team Photo"},
  {section: "Austrália", name: "Mathew Ryan"},
  {section: "Austrália", name: "Mitchell Langerak"},
  {section: "Austrália", name: "Milos Degenek"},
  {section: "Austrália", name: "Bailey Wright"},
  {section: "Austrália", name: "Aziz Behich"},
  {section: "Austrália", name: "Trent Sainsbury"},
  {section: "Austrália", name: "Ryan McGowan"},
  {section: "Austrália", name: "Mark Milligan"},
  {section: "Austrália", name: "Aaron Mooy"},
  {section: "Austrália", name: "James Troisi"},
  {section: "Austrália", name: "Mile Jedinak"},
  {section: "Austrália", name: "Massimo Luongo"},
  {section: "Austrália", name: "Jackson Irvine"},
  {section: "Austrália", name: "Tom Rogic"},
  {section: "Austrália", name: "Tim Cahill"},
  {section: "Austrália", name: "Mathew Leckie"},
  {section: "Austrália", name: "Tomi Juric"},
  {section: "Austrália", name: "Robbie Kruse"},
  {section: "Peru", name: "Peru Team Logo"},
  {section: "Peru", name: "Peru Team Photo"},
  {section: "Peru", name: "Pedro Gallese"},
  {section: "Peru", name: "Carlos Caceda"},
  {section: "Peru", name: "Aldo Corzo"},
  {section: "Peru", name: "Miguel Trauco"},
  {section: "Peru", name: "Christian Ramos"},
  {section: "Peru", name: "Luis Advincula"},
  {section: "Peru", name: "Alberto Rodriguez"},
  {section: "Peru", name: "Miguel Araujo"},
  {section: "Peru", name: "Christian Cueva"},
  {section: "Peru", name: "Renato Tapia"},
  {section: "Peru", name: "Andy Polo"},
  {section: "Peru", name: "Yoshimar Yotun"},
  {section: "Peru", name: "Edison Flores"},
  {section: "Peru", name: "Paolo Hurtado"},
  {section: "Peru", name: "Paolo Guerrero"},
  {section: "Peru", name: "Jefferson Farfan"},
  {section: "Peru", name: "Raul Ruidiaz"},
  {section: "Peru", name: "Andre Carrillo"},
  {section: "Dinamarca", name: "Denmark Team Logo"},
  {section: "Dinamarca", name: "Denmark Team Photo"},
  {section: "Dinamarca", name: "Kasper Schmeichel"},
  {section: "Dinamarca", name: "Jannik Vestergaard"},
  {section: "Dinamarca", name: "Simon Kjaer"},
  {section: "Dinamarca", name: "Andreas Christensen"},
  {section: "Dinamarca", name: "Andreas Bjelland"},
  {section: "Dinamarca", name: "Mathias Jorgensen"},
  {section: "Dinamarca", name: "Jens Stryger Larsen"},
  {section: "Dinamarca", name: "Peter Ankersen"},
  {section: "Dinamarca", name: "Riza Durmisi"},
  {section: "Dinamarca", name: "William Kvist"},
  {section: "Dinamarca", name: "Thomas Delaney"},
  {section: "Dinamarca", name: "Christian Eriksen"},
  {section: "Dinamarca", name: "Lasse Schone"},
  {section: "Dinamarca", name: "Pione Sisto"},
  {section: "Dinamarca", name: "Nicklas Bendtner"},
  {section: "Dinamarca", name: "Nicolai Jorgensen"},
  {section: "Dinamarca", name: "Yussuf Poulsen"},
  {section: "Dinamarca", name: "Andreas Cornelius"},
  {section: "Argentina", name: "Argentina Team Logo"},
  {section: "Argentina", name: "Argentina Team Photo"},
  {section: "Argentina", name: "Sergio Romero"},
  {section: "Argentina", name: "Gabriel Mercado"},
  {section: "Argentina", name: "Federico Fazio"},
  {section: "Argentina", name: "Javier Mascherano"},
  {section: "Argentina", name: "Nicolas Otamendi"},
  {section: "Argentina", name: "Marcos Rojo"},
  {section: "Argentina", name: "Ramiro Funes Mori"},
  {section: "Argentina", name: "Lucas Biglia"},
  {section: "Argentina", name: "Enzo Perez"},
  {section: "Argentina", name: "Angel Di Maria"},
  {section: "Argentina", name: "Marcos Acuna"},
  {section: "Argentina", name: "Ever Banega"},
  {section: "Argentina", name: "Eduardo Salvio"},
  {section: "Argentina", name: "Mauro Icardi"},
  {section: "Argentina", name: "Lionel Messi"},
  {section: "Argentina", name: "Paulo Dybala"},
  {section: "Argentina", name: "Sergio Aguero"},
  {section: "Argentina", name: "Gonzalo Higuain"},
  {section: "Islândia", name: "Iceland Team Logo"},
  {section: "Islândia", name: "Iceland Team Photo"},
  {section: "Islândia", name: "Hannes Halldorsson"},
  {section: "Islândia", name: "Birkir Saevarsson"},
  {section: "Islândia", name: "Ragnar Sigurdsson"},
  {section: "Islândia", name: "Kari Arnason"},
  {section: "Islândia", name: "Ari Skulason"},
  {section: "Islândia", name: "Sverrir Ingason"},
  {section: "Islândia", name: "Hordur Magnusson"},
  {section: "Islândia", name: "Aron Gunnarsson"},
  {section: "Islândia", name: "Birkir Bjarnason"},
  {section: "Islândia", name: "Emil Hallfredsson"},
  {section: "Islândia", name: "Gylfi Sigurdsson"},
  {section: "Islândia", name: "Arnor Ingvi Traustason"},
  {section: "Islândia", name: "Rurik Gislason"},
  {section: "Islândia", name: "Johann Gudmundsson"},
  {section: "Islândia", name: "Alfred Finnbogason"},
  {section: "Islândia", name: "Jon Dadi Bodvarsson"},
  {section: "Islândia", name: "Vidar Orn Kjartansson"},
  {section: "Islândia", name: "Bjorn Sigurdarson"},
  {section: "Croácia", name: "Croatia Team Logo"},
  {section: "Croácia", name: "Croatia Team Photo"},
  {section: "Croácia", name: "Danijel Subasic"},
  {section: "Croácia", name: "Sime Vrsaljko"},
  {section: "Croácia", name: "Ivan Strinic"},
  {section: "Croácia", name: "Dejan Lovren"},
  {section: "Croácia", name: "Domagoj Vida"},
  {section: "Croácia", name: "Josip Pivaric"},
  {section: "Croácia", name: "Vedran Corluka"},
  {section: "Croácia", name: "Ivan Rakitic"},
  {section: "Croácia", name: "Luka Modric"},
  {section: "Croácia", name: "Marcelo Brozovic"},
  {section: "Croácia", name: "Marko Rog"},
  {section: "Croácia", name: "Mario Pasalic"},
  {section: "Croácia", name: "Milan Badelj"},
  {section: "Croácia", name: "Mateo Kovacic"},
  {section: "Croácia", name: "Andrej Kramaric"},
  {section: "Croácia", name: "Nikola Kalinic"},
  {section: "Croácia", name: "Mario Mandzukic"},
  {section: "Croácia", name: "Ivan Perisic"},
  {section: "Nigéria", name: "Nigeria Team Logo"},
  {section: "Nigéria", name: "Nigeria Team Photo"},
  {section: "Nigéria", name: "Ikechukwu Ezenwa"},
  {section: "Nigéria", name: "Elderson Echiejile"},
  {section: "Nigéria", name: "Shehu Abdullahi"},
  {section: "Nigéria", name: "William Troost-Ekong"},
  {section: "Nigéria", name: "Leon Balogun"},
  {section: "Nigéria", name: "Kenneth Omeruo"},
  {section: "Nigéria", name: "Ola Aina"},
  {section: "Nigéria", name: "John Obi Mikel"},
  {section: "Nigéria", name: "Ogenyi Onazi"},
  {section: "Nigéria", name: "Etebo Oghenekaro"},
  {section: "Nigéria", name: "Wilfred Ndidi"},
  {section: "Nigéria", name: "Mikel Agu"},
  {section: "Nigéria", name: "Ahmed Musa"},
  {section: "Nigéria", name: "Victor Moses"},
  {section: "Nigéria", name: "Moses Simon"},
  {section: "Nigéria", name: "Odion Ighalo"},
  {section: "Nigéria", name: "Alex Iwobi"},
  {section: "Nigéria", name: "Kelechi Iheanacho"},
  {section: "Brasil", name: "Brazil Team Logo"},
  {section: "Brasil", name: "Brazil Team Photo"},
  {section: "Brasil", name: "Alisson"},
  {section: "Brasil", name: "Dani Alves"},
  {section: "Brasil", name: "Thiago Silva"},
  {section: "Brasil", name: "Miranda"},
  {section: "Brasil", name: "Filipe Luis"},
  {section: "Brasil", name: "Marquinhos"},
  {section: "Brasil", name: "Marcelo"},
  {section: "Brasil", name: "Willian"},
  {section: "Brasil", name: "Paulinho"},
  {section: "Brasil", name: "Fernandinho"},
  {section: "Brasil", name: "Casemiro"},
  {section: "Brasil", name: "Renato Augusto"},
  {section: "Brasil", name: "Giuliano"},
  {section: "Brasil", name: "Philippe Coutinho"},
  {section: "Brasil", name: "Douglas Costa"},
  {section: "Brasil", name: "Roberto Firmino"},
  {section: "Brasil", name: "Gabriel Jesus"},
  {section: "Brasil", name: "Neymar Jr"},
  {section: "Suíça", name: "Switzerland Team Logo"},
  {section: "Suíça", name: "Switzerland Team Photo"},
  {section: "Suíça", name: "Yann Sommer"},
  {section: "Suíça", name: "Stephan Lichtsteiner"},
  {section: "Suíça", name: "Manuel Akanji"},
  {section: "Suíça", name: "Michael Lang"},
  {section: "Suíça", name: "Ricardo Rodriguez"},
  {section: "Suíça", name: "Johan Djourou"},
  {section: "Suíça", name: "Fabian Schar"},
  {section: "Suíça", name: "Granit Xhaka"},
  {section: "Suíça", name: "Steven Zuber"},
  {section: "Suíça", name: "Blerim Dzemaili"},
  {section: "Suíça", name: "Denis Zakaria"},
  {section: "Suíça", name: "Xherdan Shaqiri"},
  {section: "Suíça", name: "Valon Behrami"},
  {section: "Suíça", name: "Gelson Fernandes"},
  {section: "Suíça", name: "Breel Embolo"},
  {section: "Suíça", name: "Haris Seferovic"},
  {section: "Suíça", name: "Admir Mehmedi"},
  {section: "Suíça", name: "Eren Derdiyok"},
  {section: "Costa Rica", name: "Costa Rica Team Logo"},
  {section: "Costa Rica", name: "Costa Rica Team Photo"},
  {section: "Costa Rica", name: "Keylor Navas"},
  {section: "Costa Rica", name: "Giancarlo Gonzalez"},
  {section: "Costa Rica", name: "Cristian Gamboa"},
  {section: "Costa Rica", name: "Bryan Oviedo"},
  {section: "Costa Rica", name: "Francisco Calvo"},
  {section: "Costa Rica", name: "Kendall Waston"},
  {section: "Costa Rica", name: "Ronald Matarrita"},
  {section: "Costa Rica", name: "Michael Umana"},
  {section: "Costa Rica", name: "Johnny Acosta"},
  {section: "Costa Rica", name: "Bryan Ruiz"},
  {section: "Costa Rica", name: "Celso Borges"},
  {section: "Costa Rica", name: "Christian Bolanos"},
  {section: "Costa Rica", name: "Randall Azofeifa"},
  {section: "Costa Rica", name: "David Guzman"},
  {section: "Costa Rica", name: "Rodney Wallace"},
  {section: "Costa Rica", name: "Joel Campbell"},
  {section: "Costa Rica", name: "Marco Urena"},
  {section: "Costa Rica", name: "Johan Venegas"},
  {section: "Sérvia", name: "Serbia Team Logo"},
  {section: "Sérvia", name: "Serbia Team Photo"},
  {section: "Sérvia", name: "Vladimir Stojkovic"},
  {section: "Sérvia", name: "Branislav Ivanovic"},
  {section: "Sérvia", name: "Aleksandar Kolarov"},
  {section: "Sérvia", name: "Antonio Rukavina"},
  {section: "Sérvia", name: "Matija Nastasic"},
  {section: "Sérvia", name: "Dusko Tosic"},
  {section: "Sérvia", name: "Nikola Maksimovic"},
  {section: "Sérvia", name: "Jagos Vukovic"},
  {section: "Sérvia", name: "Dusan Tadic"},
  {section: "Sérvia", name: "Sergej Milinkovic-Savic"},
  {section: "Sérvia", name: "Nemanja Matic"},
  {section: "Sérvia", name: "Luka Milivojevic"},
  {section: "Sérvia", name: "Adem Ljajic"},
  {section: "Sérvia", name: "Nemanja Gudelj"},
  {section: "Sérvia", name: "Mijat Gacinovic"},
  {section: "Sérvia", name: "Filip Kostic"},
  {section: "Sérvia", name: "Aleksandar Mitrovic"},
  {section: "Sérvia", name: "Aleksandar Prijovic"},
  {section: "Alemanha", name: "Germany Team Logo"},
  {section: "Alemanha", name: "Germany Team Photo"},
  {section: "Alemanha", name: "Manuel Neuer"},
  {section: "Alemanha", name: "Mats Hummels"},
  {section: "Alemanha", name: "Antonio Rudiger"},
  {section: "Alemanha", name: "Jerome Boateng"},
  {section: "Alemanha", name: "Joshua Kimmich"},
  {section: "Alemanha", name: "Jonas Hector"},
  {section: "Alemanha", name: "Julian Draxler"},
  {section: "Alemanha", name: "Toni Kroos"},
  {section: "Alemanha", name: "Emre Can"},
  {section: "Alemanha", name: "Leon Goretzka"},
  {section: "Alemanha", name: "Julian Brandt"},
  {section: "Alemanha", name: "Sebastian Rudy"},
  {section: "Alemanha", name: "Leroy Sane"},
  {section: "Alemanha", name: "Mesut Ozil"},
  {section: "Alemanha", name: "Sami Khedira"},
  {section: "Alemanha", name: "Mario Gotze"},
  {section: "Alemanha", name: "Thomas Muller"},
  {section: "Alemanha", name: "Timo Werner"},
  {section: "México", name: "Mexico Team Logo"},
  {section: "México", name: "Mexico Team Photo"},
  {section: "México", name: "Guillermo Ochoa"},
  {section: "México", name: "Hugo Ayala"},
  {section: "México", name: "Diego Reyes"},
  {section: "México", name: "Hector Moreno"},
  {section: "México", name: "Jesus Gallardo"},
  {section: "México", name: "Miguel Layun"},
  {section: "México", name: "Carlos Salcedo"},
  {section: "México", name: "Jonathan dos Santos"},
  {section: "México", name: "Giovani dos Santos"},
  {section: "México", name: "Andres Guardado"},
  {section: "México", name: "Hector Herrera"},
  {section: "México", name: "Javier Aquino"},
  {section: "México", name: "Jesus Corona"},
  {section: "México", name: "Hirving Lozano"},
  {section: "México", name: "Raul Jimenez"},
  {section: "México", name: "Carlos Vela"},
  {section: "México", name: "Javier Hernandez"},
  {section: "México", name: "Oribe Peralta"},
  {section: "Suécia", name: "Sweden Team Logo"},
  {section: "Suécia", name: "Sweden Team Photo"},
  {section: "Suécia", name: "Robin Olsen"},
  {section: "Suécia", name: "Mikael Lustig"},
  {section: "Suécia", name: "Victor Nilsson Lindelof"},
  {section: "Suécia", name: "Andreas Granqvist"},
  {section: "Suécia", name: "Martin Olsson"},
  {section: "Suécia", name: "Ludwig Augustinsson"},
  {section: "Suécia", name: "Emil Krafth"},
  {section: "Suécia", name: "Pontus Jansson"},
  {section: "Suécia", name: "Sebastian Larsson"},
  {section: "Suécia", name: "Emil Forsberg"},
  {section: "Suécia", name: "Gustav Svensson"},
  {section: "Suécia", name: "Viktor Claesson"},
  {section: "Suécia", name: "Jimmy Durmaz"},
  {section: "Suécia", name: "Albin Ekdal"},
  {section: "Suécia", name: "Isaac Kiese Thelin"},
  {section: "Suécia", name: "Marcus Berg"},
  {section: "Suécia", name: "John Guidetti"},
  {section: "Suécia", name: "Ola Toivonen"},
  {section: "Coréia", name: "Korea Republic Team Logo"},
  {section: "Coréia", name: "Korea Republic Team Photo"},
  {section: "Coréia", name: "Kim Seunggyu"},
  {section: "Coréia", name: "Kim Younggwon"},
  {section: "Coréia", name: "Kim Jinsu"},
  {section: "Coréia", name: "Kwak Taehwi"},
  {section: "Coréia", name: "Hong Jeongho"},
  {section: "Coréia", name: "Jang Hyunsoo"},
  {section: "Coréia", name: "Koo Jacheol"},
  {section: "Coréia", name: "Kwon Changhoon"},
  {section: "Coréia", name: "Ki Sungyueng"},
  {section: "Coréia", name: "Nam Taehee"},
  {section: "Coréia", name: "Han Kookyoung"},
  {section: "Coréia", name: "Lee Chungyong"},
  {section: "Coréia", name: "Jung Wooyoung"},
  {section: "Coréia", name: "Lee Jaesung"},
  {section: "Coréia", name: "Son Heungmin"},
  {section: "Coréia", name: "Ji Dongwon"},
  {section: "Coréia", name: "Kim Shinwook"},
  {section: "Coréia", name: "Hwang Heechan"},
  {section: "Bélgica", name: "Belgium Team Logo"},
  {section: "Bélgica", name: "Belgium Team Photo"},
  {section: "Bélgica", name: "Thibaut Courtois"},
  {section: "Bélgica", name: "Toby Alderweireld"},
  {section: "Bélgica", name: "Thomas Vermaelen"},
  {section: "Bélgica", name: "Jan Vertonghen"},
  {section: "Bélgica", name: "Vincent Kompany"},
  {section: "Bélgica", name: "Thomas Meunier"},
  {section: "Bélgica", name: "Axel Witsel"},
  {section: "Bélgica", name: "Radja Nainggolan"},
  {section: "Bélgica", name: "Kevin De Bruyne"},
  {section: "Bélgica", name: "Marouane Fellaini"},
  {section: "Bélgica", name: "Youri Tielemans"},
  {section: "Bélgica", name: "Mousa Dembele"},
  {section: "Bélgica", name: "Nacer Chadli"},
  {section: "Bélgica", name: "Eden Hazard"},
  {section: "Bélgica", name: "Yannick Carrasco"},
  {section: "Bélgica", name: "Dries Mertens"},
  {section: "Bélgica", name: "Michy Batshuayi"},
  {section: "Bélgica", name: "Romelu Lukaku"},
  {section: "Panamá", name: "Panama Team Logo"},
  {section: "Panamá", name: "Panama Team Photo"},
  {section: "Panamá", name: "Jaime Penedo"},
  {section: "Panamá", name: "Jose Calderon"},
  {section: "Panamá", name: "Michael Murillo"},
  {section: "Panamá", name: "Fidel Escobar"},
  {section: "Panamá", name: "Roman Torres"},
  {section: "Panamá", name: "Adolfo Machado"},
  {section: "Panamá", name: "Eric Davis"},
  {section: "Panamá", name: "Luis Ovalle"},
  {section: "Panamá", name: "Felipe Baloy"},
  {section: "Panamá", name: "Gabriel Gomez"},
  {section: "Panamá", name: "Edgar Barcenas"},
  {section: "Panamá", name: "Armando Cooper"},
  {section: "Panamá", name: "Alberto Quintero"},
  {section: "Panamá", name: "Anibal Godoy"},
  {section: "Panamá", name: "Blas Perez"},
  {section: "Panamá", name: "Gabriel Torres"},
  {section: "Panamá", name: "Luis Tejada"},
  {section: "Panamá", name: "Abdiel Arroyo"},
  {section: "Tunísia", name: "Tunisia Team Logo"},
  {section: "Tunísia", name: "Tunisia Team Photo"},
  {section: "Tunísia", name: "Aymen Mathlouthi"},
  {section: "Tunísia", name: "Ali Maaloul"},
  {section: "Tunísia", name: "Syam Ben Youssef"},
  {section: "Tunísia", name: "Aymen Abdennour"},
  {section: "Tunísia", name: "Hamdi Naguez"},
  {section: "Tunísia", name: "Yassine Meriah"},
  {section: "Tunísia", name: "Oussama Haddadi"},
  {section: "Tunísia", name: "Ferjani Sassi"},
  {section: "Tunísia", name: "Wahbi Khazri"},
  {section: "Tunísia", name: "Mohamed Amine Ben Amor"},
  {section: "Tunísia", name: "Ghaylene Chaalali"},
  {section: "Tunísia", name: "Naim Sliti"},
  {section: "Tunísia", name: "Youssef Msakni"},
  {section: "Tunísia", name: "Fakhreddine Ben Youssef"},
  {section: "Tunísia", name: "Taha Yassine Khenissi"},
  {section: "Tunísia", name: "Yoann Touzghar"},
  {section: "Tunísia", name: "Anice Badri"},
  {section: "Tunísia", name: "Ahmed Akaichi"},
  {section: "Inglaterra", name: "England Team Logo"},
  {section: "Inglaterra", name: "England Team Photo"},
  {section: "Inglaterra", name: "Joe Hart"},
  {section: "Inglaterra", name: "Jordan Pickford"},
  {section: "Inglaterra", name: "Gary Cahill"},
  {section: "Inglaterra", name: "Kyle Walker"},
  {section: "Inglaterra", name: "John Stones"},
  {section: "Inglaterra", name: "Ryan Bertrand"},
  {section: "Inglaterra", name: "Danny Rose"},
  {section: "Inglaterra", name: "Phil Jones"},
  {section: "Inglaterra", name: "Jordan Henderson"},
  {section: "Inglaterra", name: "Alex Oxlade-Chamberlain"},
  {section: "Inglaterra", name: "Dele Alli"},
  {section: "Inglaterra", name: "Eric Dier"},
  {section: "Inglaterra", name: "Adam Lallana"},
  {section: "Inglaterra", name: "Jesse Lingard"},
  {section: "Inglaterra", name: "Raheem Sterling"},
  {section: "Inglaterra", name: "Harry Kane"},
  {section: "Inglaterra", name: "Marcus Rashford"},
  {section: "Inglaterra", name: "Jamie Vardy"},
  {section: "Polônia", name: "Poland Team Logo"},
  {section: "Polônia", name: "Poland Team Photo"},
  {section: "Polônia", name: "Lukasz Fabianski"},
  {section: "Polônia", name: "Wojciech Szczesny"},
  {section: "Polônia", name: "Lukasz Piszczek"},
  {section: "Polônia", name: "Kamil Glik"},
  {section: "Polônia", name: "Michal Pazdan"},
  {section: "Polônia", name: "Thiago Cionek"},
  {section: "Polônia", name: "Bartosz Bereszynski"},
  {section: "Polônia", name: "Artur Jedrzejczyk"},
  {section: "Polônia", name: "Maciej Rybus"},
  {section: "Polônia", name: "Jakub Blaszczykowski"},
  {section: "Polônia", name: "Kamil Grosicki"},
  {section: "Polônia", name: "Grzegorz Krychowiak"},
  {section: "Polônia", name: "Krzysztof Maczynski"},
  {section: "Polônia", name: "Piotr Zielinski"},
  {section: "Polônia", name: "Karol Linetty"},
  {section: "Polônia", name: "Robert Lewandowski"},
  {section: "Polônia", name: "Lukasz Teodorczyk"},
  {section: "Polônia", name: "Arkadiusz Milik"},
  {section: "Senegal", name: "Senegal Team Logo"},
  {section: "Senegal", name: "Senegal Team Photo"},
  {section: "Senegal", name: "Khadim N’Diaye"},
  {section: "Senegal", name: "Kara Mbodj"},
  {section: "Senegal", name: "Lamine Gassama"},
  {section: "Senegal", name: "Kalidou Koulibaly"},
  {section: "Senegal", name: "Salif Sane"},
  {section: "Senegal", name: "Saliou Ciss"},
  {section: "Senegal", name: "Moussa Wague"},
  {section: "Senegal", name: "Idrissa Gueye"},
  {section: "Senegal", name: "Cheikhou Kouyate"},
  {section: "Senegal", name: "Cheikh Ndoye"},
  {section: "Senegal", name: "Papa Alioune N’Diaye"},
  {section: "Senegal", name: "Sadio Mane"},
  {section: "Senegal", name: "Moussa Sow"},
  {section: "Senegal", name: "Moussa Konate"},
  {section: "Senegal", name: "Keita Balde"},
  {section: "Senegal", name: "M’Baye Niang"},
  {section: "Senegal", name: "Ismaila Sarr"},
  {section: "Senegal", name: "Mame Diouf"},
  {section: "Colômbia", name: "Colombia Team Logo"},
  {section: "Colômbia", name: "Colombia Team Photo"},
  {section: "Colômbia", name: "David Ospina"},
  {section: "Colômbia", name: "Cristian Zapata"},
  {section: "Colômbia", name: "Santiago Arias"},
  {section: "Colômbia", name: "Frank Fabra"},
  {section: "Colômbia", name: "Davinson Sanchez"},
  {section: "Colômbia", name: "Yerry Mina"},
  {section: "Colômbia", name: "Carlos Sanchez"},
  {section: "Colômbia", name: "Juan Guillermo Cuadrado"},
  {section: "Colômbia", name: "Abel Aguilar"},
  {section: "Colômbia", name: "James Rodriguez"},
  {section: "Colômbia", name: "Giovanni Moreno"},
  {section: "Colômbia", name: "Wilmar Barrios"},
  {section: "Colômbia", name: "Radamel Falcao Garcia"},
  {section: "Colômbia", name: "Teofilo Gutierrez"},
  {section: "Colômbia", name: "Carlos Bacca"},
  {section: "Colômbia", name: "Edwin Cardona"},
  {section: "Colômbia", name: "Yimmi Chara"},
  {section: "Colômbia", name: "Duvan Zapata"},
  {section: "Japão", name: "Japan Team Logo"},
  {section: "Japão", name: "Japan Team Photo"},
  {section: "Japão", name: "Eiji Kawashima"},
  {section: "Japão", name: "Shusaku Nishikawa"},
  {section: "Japão", name: "Masato Morishige"},
  {section: "Japão", name: "Yuto Nagatomo"},
  {section: "Japão", name: "Hiroki Sakai"},
  {section: "Japão", name: "Tomoaki Makino"},
  {section: "Japão", name: "Gotoku Sakai"},
  {section: "Japão", name: "Maya Yoshida"},
  {section: "Japão", name: "Hotaru Yamaguchi"},
  {section: "Japão", name: "Shinji Kagawa"},
  {section: "Japão", name: "Makoto Hasebe"},
  {section: "Japão", name: "Hiroshi Kiyotake"},
  {section: "Japão", name: "Keisuke Honda"},
  {section: "Japão", name: "Takashi Usami"},
  {section: "Japão", name: "Genki Haraguchi"},
  {section: "Japão", name: "Shinji Okazaki"},
  {section: "Japão", name: "Yuya Kubo"},
  {section: "Japão", name: "Yuya Osako"},
  {section: "Clássicos", name: "58 Brazil WCL"},
  {section: "Clássicos", name: "14 Germany WCL"},
  {section: "Clássicos", name: "82 Italy WCL"},
  {section: "Clássicos", name: "30 Uruguay WCL"},
  {section: "Clássicos", name: "86 Argentina WCL"},
  {section: "Clássicos", name: "66 England WCL"},
  {section: "Clássicos", name: "98 France WCL"},
  {section: "Clássicos", name: "10 Spain WCL"},
  {section: "Clássicos", name: "Pele WCL"},
  {section: "Clássicos", name: "Miroslav Klose WCL"}
].map((sticker, index) => ({ ...sticker, count: 0, stickerNumber: index }));
